name: Generate Custom Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Generar SVG personalizado
        run: |
          USER="Jaminton2007"

          REPOS=$(curl -s https://api.github.com/users/$USER | jq .public_repos)
          FOLLOWERS=$(curl -s https://api.github.com/users/$USER | jq .followers)

          cat <<EOF > github-stats.svg
          <svg width="400" height="120" xmlns="http://www.w3.org/2000/svg">
            <style>
              .title { font: bold 18px sans-serif; }
              .text { font: 14px sans-serif; }
            </style>

            <text x="10" y="25" class="title">GitHub Stats</text>
            <text x="10" y="55" class="text">User: $USER</text>
            <text x="10" y="75" class="text">Repos: $REPOS</text>
            <text x="10" y="95" class="text">Followers: $FOLLOWERS</text>
          </svg>
          EOF

      - name: Guardar cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add github-stats.svg
          git commit -m "update custom stats" || exit 0
          git push
